version: "3"
services:
  spark:
    build: .

    environment:
      - AWS_ACCESS_KEY_ID=dummy
      - AWS_SECRET_ACCESS_KEY=dummy
      - AWS_REGION=ap-northeast-1
      - AWS_DEFAULT_REGION=ap-northeast-1

    tty: true
    stdin_open: true

  localstack:
    image: localstack/localstack:0.12.3
    # image: localstack/localstack:0.11.2
    ports:
      - "4566:4566"
      # - "4571:4571"
      - "4567-4597:4567-4597"
    environment:
      - DOCKER_HOST=unix:///var/run/docker.sock
      - DEFAULT_REGION=ap-northeast-1
